name: Pr Review
on: [pull_request]

env:
  CI: true
  VERSION: ${{ github.event.pull_request.number }}

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn typescript
      - run: yarn lint
      - run: yarn test
